### PR TITLE
fix: relative links

### PR DESCRIPTION
**Pull request by mmiask**
Fixes: https://github.com/stoplightio/platform-internal/issues/7098

### CODE REVIEW

**Review by mpodlasin — APPROVED** [review]
🎉

**Review by marcelltoth — COMMENTED** [review]
lol, was that it? 😮 I thought it was going to be much more complicated 😄 Good job @mmiask !!!

**Comment by marbemac** [comment]
@marcelltoth @mmiask quick note - `markdown-viewer` has this sort of markdown component override provider built in now (https://github.com/stoplightio/markdown-viewer/pull/95). Could switch to using it rather than the custom one here in elements, and get a nice code reduction win here. The one built into markdown-viewer also has benefit that the custom components will be leveraged even when markdown viewer is rendered in downstream components (for example markdown rendered in json schema viewer descriptions, etc).

**Comment by mmiask** [comment]
> @marcelltoth @mmiask quick note - `markdown-viewer` has this sort of markdown component override provider built in now ([stoplightio/markdown-viewer#95](https://github.com/stoplightio/markdown-viewer/pull/95)). Could switch to using it rather than the custom one here in elements, and get a nice code reduction win here. The one built into markdown-viewer also has benefit that the custom components will be leveraged even when markdown viewer is rendered in downstream components (for example markdown rendered in json schema viewer descriptions, etc).

Oh, nice - I'll definitely check it out, thanks! No need in having custom ones if there's one already in MDV 👍

**Pull request merged**
