### PR TITLE
"Elements" Web Components Support For ESM

### PR DESCRIPTION
**Pull request by aerialist7**
Hi Team,

we're using `@stoplight/elements` web components in [Vite/React project](https://github.com/aerialist7/stoplight-elements-sample/tree/vite-react-web-component).
But there is unpleasant error while run `build` or `dev` commands:
```
[vite:resolve] Missing "./web-components.min.js" export in "@stoplight/elements" package
error during build:
Error: Missing "./web-components.min.js" export in "@stoplight/elements" package
```
That's [caused by Vite's strict adherence to the exports field in the package.json](https://github.com/vitejs/vite/issues/6480#issuecomment-1011937533).

So here is a fix for this problem.

### CODE REVIEW

**Comment by aerialist7** [comment]
cc @lottamus @philsturgeon @ryotrellim @heitortsergent @marcelltoth

**Comment by aerialist7** [comment]
Hi @pamgoodrich @lottamus @Nezteb @marbemac!
Can anyone please review my PR?

**Review by lottamus — CHANGES_REQUESTED** [review]
@aerialist7 thanks for the PR. Why did you decide to use the web-components build in your React app versus the React components? The web-components are primarily meant for non-React apps and are less flexible than the React components.


For https://github.com/aerialist7/stoplight-elements-sample/blob/vite-react-web-component/src/App.tsx, instead you could do the following:

```tsx
import { API } from '@stoplight/elements'
import '@stoplight/elements/styles.min.css'
import './App.css'

function App() {
  return (
    <div className="App">
      <API
        apiDescriptionUrl="https://raw.githubusercontent.com/stoplightio/Public-APIs/master/reference/zoom/openapi.yaml"
      />
    </div>
  )
}

export default App
```

**Comment by aerialist7** [comment]
Hi @lottamus, thank you for respond!

Sure, I've tried to use React component at the beginning. But the app doesn't work.

Here you can see my sample
- https://github.com/aerialist7/stoplight-elements-sample/tree/vite-react-component

Run `dev` or `preview` commands and open browser console - ```Uncaught ReferenceError: require is not defined```

Then I've tried to use it as Web Component

**Comment by aerialist7** [comment]
Hi @lottamus, can you please answer?

**Comment by lottamus** [comment]
@aerialist7 I've tried your Vitejs example and see it's not working out of the box. I'm not as familiar with Vite and esbuild, so I'll need to investigate to see what config options are needed to support Elements. Ideally it's just supported out of the box 😞 

Initial findings:
- Seems related to `require is not defined`: https://github.com/vitejs/vite/issues/3409
- Might need to add a `commonjs` plugin targeting Elements: https://vitejs.dev/guide/dep-pre-bundling.html#the-why

**Comment by aerialist7** [comment]
@lottamus, thank you! 

It would be great and we hope that it will be supported out of the box!
But now we can't use even Web Component variant without hacks. 
So could you please merge my PR and release the new version of Stoplight "Elements"?

**Comment by aerialist7** [comment]
Hi @lottamus, can you please answer?

**Comment by lottamus** [comment]
@aerialist7 I've been able to successfully run `npm run dev` on your branch using the following vitejs config:

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
import NodeModulesPolyfills from "@esbuild-plugins/node-modules-polyfill";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],

  optimizeDeps: {
    esbuildOptions: {
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
          process: true,
        }),
        NodeModulesPolyfills(),
      ],
    },
  },
});
```

Make sure to install the two additional dev deps `@esbuild-plugins/node-globals-polyfill` and `@esbuild-plugins/node-modules-polyfill`.

Now that `dev` is working, I have a better hunch on why the prod build `npm run build && serve -s dist` is not working, but I've not yet come to the right config. I'm still hitting this issue: https://github.com/vitejs/vite/issues/2672

**Comment by aerialist7** [comment]
@lottamus I applied your configuration [here](https://github.com/aerialist7/stoplight-elements-sample/tree/vite-react-component)

Thank you, `dev` works, but with problems:
# unable to select anything in the sidebar
# warnings in the browser console (mb related to first problem)

Yep, It doesn't work for me in `prod` either.
Crashes in runtime with the following error:
```
Uncaught ReferenceError: require is not defined
    at index.4675c23e.js:768:3139
    at index.4675c23e.js:1:644
    at index.4675c23e.js:1044:71129
```

**Review by marcelltoth — APPROVED** [review]
I don't have write access here anymore but I believe that this change is fundamentally correct, and the fact that the React distribution does or does not work with Vite should be a separate topic. (Tracked in an issue,)

@lottamus We explicitly support using the web components distribution, then why are you so hesitant to approve a PR that makes the statement `import '@stoplight/elements/web-components.min.js'` legal under the Node ESM spec? Would you like to restrict web components usage to direct script tag usage for some reason?

Now for the bug itself, I think that should be handled separately, but in the meantime I think I have a workaround for @aerialist7: try adding it the old-school way, using a script tag in the `<head>`. That does work I believe, even when using React, why wouldn't it.

**Comment by aerialist7** [comment]
@lottamus, any news? 
May be we really can continue merge this PR and continue our discussion within separate issue? (e.g. #2076)

**Comment by aerialist7** [comment]
@lottamus

**Review by lottamus — APPROVED** [review]

**Comment by aerialist7** [comment]
@lottamus, thank you!
When we can expect a new release?

**Comment by aerialist7** [comment]
@lottamus

**Pull request merged**
