### PR TITLE
chore: no more petstore

### PR DESCRIPTION
**Pull request by philsturgeon**

### CODE REVIEW

**Comment by marcelltoth** [comment]
What's the rationale?

**Comment by philsturgeon** [comment]
The rationale is the pet store is not a good example of anything so let’s not use it as an example for anything. People generally hate the pet store and I keep getting messages about it.

**Review by marcelltoth — APPROVED** [review]
I liked it as the simplest thing to try new features with first, but I get it

**Comment by philsturgeon** [comment]
Yeah, keep the URL around along with some other good URLs. I have a bookmark folder in Firefox!

**Pull request merged**
