### PR TITLE
feat: add scss to core build

### PR DESCRIPTION
**Pull request by mallachari**
Add scss to elements-core build. Elements and elements-dev-portal are left with just css

### CODE REVIEW

**Review by mpodlasin — APPROVED** [review]
Tested it and it works well.

**Comment by philsturgeon** [comment]
This looks like it’s just adding something, but don’t we need to also remove something from somewhere, or is this the first time we’ve used SCSS?

**Comment by mpodlasin** [comment]
> This looks like it’s just adding something, but don’t we need to also remove something from somewhere, or is this the first time we’ve used SCSS?

This is - most likely - temporary solution. We can't use our css in platform, because this would double mosaic and uikit styles. Once uikit is gone, this sass will be come css (and perhaps it will change into a single stylesheet.

In other words `elements.min.css = elements styles + mosaic`. But we need "elements only" styles as well.

**Comment by mallachari** [comment]
We've removed scss before from built packages assuming that styles.min.css is enough, but they will be useful in platform so I added them back just for elements-core.

**Pull request merged**
