### PR TITLE
feat: response body format and images

### PR DESCRIPTION
**Pull request by mallachari**
Addresses: https://github.com/stoplightio/elements/issues/649

Adds response body format (`Preview`, `Raw`) support depending on `content-type`.
Adds support for displaying response images.

I've moved the `Response` component to a separate file as it got too big. Some parts of it remain the same but there's plenty added.

https://user-images.githubusercontent.com/14196079/131678365-d45f2004-ee4b-4b10-955a-198de868061b.mov

https://user-images.githubusercontent.com/14196079/131678387-aba61b53-24cb-433f-b291-dc78f51d4e8d.mov

https://user-images.githubusercontent.com/14196079/131679073-10c7c426-bc69-4184-bc77-b477ab419110.mov

https://user-images.githubusercontent.com/14196079/131679092-c43b4bca-9e45-43cd-9cc1-d0ecd5a4d264.mov

### CODE REVIEW

**Review by mnaumanali94 — APPROVED** [review]
<3

**Review by domagojk — APPROVED** [review]
Code looks good, and it works! 💪

**Review by mpodlasin — APPROVED** [review]
Solid work! 💪

**Comment by wmhilton** [comment]
Why did we artificially limit the kinds of images supported?

```
  image: /image\/(.+)*(jpeg|gif|png|svg)/,
```

Why not

```
  image: /^image(\/.+)?/,
```

?

I only ask because well, the user-images API serves all its images with `Content-Type: image`. Because it works and I was lazy.

**Pull request merged**
