### PR TITLE
fix: issue of internal and exterrnal links in article

### PR DESCRIPTION
**Pull request by SB-venkatyadavilli**
## Addressed
STOP-1073

## Description
fixed the issue of Devportal Links between the article.

## Testing
I have tested it manually and also tested in the platform-internal using Yalc.

### Before fix:

https://github.com/user-attachments/assets/b11584a8-5cb5-422e-96f2-f8c81ee0f5ce

### After fix:

https://github.com/user-attachments/assets/f3a033de-8b83-43df-b9ef-8407c2f67578

### CODE REVIEW

**Comment by ben-smartbear** [comment]
please add a test for this

**Comment by SB-venkatyadavilli** [comment]
> please add a test for this
@ben-smartbear i have added the screen recording of before and after the fix.

**Review by SB-akshaythakar — APPROVED** [review]

**Comment by ben-smartbear** [comment]
i don't see the requested unit test for this?

**Comment by SB-venkatyadavilli** [comment]
> i don't see the requested unit test for this?
development is in progress

**Comment by SB-venkatyadavilli** [comment]
@ben-smartbear , have added Unit test case, can you please re-review?

**Review by ben-smartbear — APPROVED** [review]

**Pull request merged**
