### PR TITLE
Add types field to exports in package.json

### PR DESCRIPTION
**Pull request by jigsawye**
When TypeScript's `moduleResolution` is set to `bundler`, it uses `exports` to resolve types. The absence of a `types` field can result in TypeScript not being able to locate the declaration file.

screencapture 2023-08-29 下午2 55 00

### CODE REVIEW

**Comment by billiegoose** [comment]
Oooh! OK. Do we need to add `types` to `elements-core` and `elements-dev-portal` too?

**Comment by jigsawye** [comment]
@billiegoose I've noticed that the `exports` field gets overwritten by `@stoplight/scripts` during release. Perhaps we should consider adjusting this part?

https://github.com/stoplightio/scripts/blob/da54218e769ab2ab5094ee9f794d4ebbbd4a90cc/src/commands/bundle/index.ts#L50-L67

**Comment by simonbs** [comment]
Is there any update on this? I'm seeing the same issue when using @stoplight/elements a Next.js project.

**Comment by chentsulin** [comment]
According to the doc: https://nodejs.org/api/packages.html#community-conditions-definitions

"types" should always be included first.

**Review by mallachari — APPROVED** [review]

**Comment by dapuicon** [comment]
Hi @chohmann!

This PR has been merged, but the change is not being reflected in the published package. In [npm](https://www.npmjs.com/package/@stoplight/elements/v/8.1.0?activeTab=code) and my local I see:

```json
...
"exports": {
    "./styles.min.css": "./styles.min.css",
    "./web-components.min.js": "./web-components.min.js",
    ".": {
      "require": "./index.js",
      "import": "./index.mjs"
    }
  }
...
```
Maybe is happening what @billiegoose  mentioned:

> @billiegoose I've noticed that the `exports` field gets overwritten by `@stoplight/scripts` during release. Perhaps we should consider adjusting this part?
> 
> https://github.com/stoplightio/scripts/blob/da54218e769ab2ab5094ee9f794d4ebbbd4a90cc/src/commands/bundle/index.ts#L50-L67

Should I open an issue? Thanks

**Comment by jigsawye** [comment]
> Hi @chohmann!
> 
> This PR has been merged, but the change is not being reflected in the published package. In [npm](https://www.npmjs.com/package/@stoplight/elements/v/8.1.0?activeTab=code) and my local I see:
> 
> ```json
> ...
> "exports": {
>     "./styles.min.css": "./styles.min.css",
>     "./web-components.min.js": "./web-components.min.js",
>     ".": {
>       "require": "./index.js",
>       "import": "./index.mjs"
>     }
>   }
> ...
> ```
> 
> Maybe is happening what @billiegoose mentioned:
> 
> > @billiegoose I've noticed that the `exports` field gets overwritten by `@stoplight/scripts` during release. Perhaps we should consider adjusting this part?
> > [stoplightio/scripts@`da54218`/src/commands/bundle/index.ts#L50-L67](https://github.com/stoplightio/scripts/blob/da54218e769ab2ab5094ee9f794d4ebbbd4a90cc/src/commands/bundle/index.ts#L50-L67)
> 
> Should I open an issue? Thanks

@dapuicon Perhaps this is what you're looking for?
https://github.com/stoplightio/scripts/pull/115

**Pull request merged**
