### PR TITLE
fix: don't add "undefined" to the end of links

### LINKED ISSUE #1969: Internal links are broken
## Describe the bug

Internal links (links between items in Stoplight) are broken, and instead show as just links to the current page. 

## To Reproduce

1. Link between one document and another in Stoplight
2. Render using Stoplight Elements
3. Link will show current URL not the destination URL

In Stoplight studio the link will be `{correctURL}undefined` which might be a hint as to what is happening.

## Expected behavior

Expected behavior is for the link to be converted to the appropriate URL from the stoplight internal reference schema.

image
image
image

gz#7708<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/7708'>Zendesk ticket #7708</a>)</i>

### PR DESCRIPTION
**Pull request by wmhilton**
@jgreen44 pointed me to the line. I'm like, 95% confident this will fix #1969.

Update: I have tested it by yalcing dev portal into platform-internal and confirm it does the trick.

### CODE REVIEW

**Comment by estrattonbailey** [comment]
🙏

**Review by mpodlasin — APPROVED** [review]
😅

**Review by Nezteb — APPROVED** [review]
Tests? :trollface:

**Review by jgreen44 — APPROVED** [review]

**Comment by fsargent** [comment]
Not sure if this is a test of this, but  on https://deploy-preview-1973--stoplight-elements-dev-portal-storybook.netlify.app/?path=/docs/public-stoplightproject--playground
this URL doesn't navigate
image

**Comment by fsargent** [comment]
This issue isn't resolved. I'm still seeing errors. This now occurs when clicking the link.
image

**Pull request merged**
