### PR TITLE
Release/12

### PR DESCRIPTION
**Pull request by KyleJohnst**
# Elements Default PR Template

In general, make sure you have: (check the boxes to acknowledge you've followed this template)

- [ ] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)

#### Other Available PR Templates:

- Release: https://github.com/stoplightio/elements/compare?template=release.md
  - [ ] [Read the release section of `CONTRIBUTING.md`](../CONTRIBUTING.md#releasing-elements)

### CODE REVIEW

**Comment by mnaumanali94** [comment]
@KyleJohnst I'm guessing this is not intended :D

**Comment by KyleJohnst** [comment]
> @KyleJohnst I'm guessing this is not intended :D 
> 
> 

Correct, wrong repo sorry! Will close!

**Comment by mnaumanali94** [comment]
@KyleJohnst We'd love any contributions that y'all think would be nice for the community

**Comment by KyleJohnst** [comment]
It has been spoken about and I am sure we can get some stuff back to you guys at some point as we love the project :D

**Pull request closed without merging**
