### PR TITLE
fix: service tag names losing casing

### LINKED ISSUE #2031: Service level tags cause navigation to always be lower-case
## Describe the bug

When using both service level tags & path level tags the rendering logic seems to be a bit skewed.

When for example you only have path level tag called: "My Tag" it will correctly render as such in the navigation bar. However when you include "My Tag" in the global `tags` list (for example to dictate the render order) it actually renders as "my tag" in the navigation bar.

This seems to be the "offending" code:
https://github.com/stoplightio/elements/blob/main/packages/elements/src/components/API/utils.ts#L26

Was this a deliberate decision? If not then I'm more than happy to contribute a fix for this 😄 

## To Reproduce

1. Open the stoplight demo with [this](https://gist.githubusercontent.com/bastuijnman/2b1e17be28aea4559a01e71b63b3fa53/raw/b2c0b3f923e8487c63db09ecf3dde68f168aa191/openapi.yaml) openapi spec
2. See "My Example" rendered in the navigation
3. Open the stoplight demo with [this](https://gist.githubusercontent.com/bastuijnman/2b1e17be28aea4559a01e71b63b3fa53/raw/b2c0b3f923e8487c63db09ecf3dde68f168aa191/openapi-bug.yaml) openapi spec
4. See "my example" rendered in the navigation

## Expected behavior

"My Example" rendered in the navigation for both cases.

## Additional context
None

### PR DESCRIPTION
**Pull request by bastuijnman**
This PR fixes #2031 and adds 2 new test cases:

- Whether service level tag casing is preserved
- Whether tags are matched case-insensitive

The second test case I assumed from code that in fact that needs to happen, but feel free to correct me if I'm wrong there 😅 

I've opted for a change that just finds the index in the mapped array & then uses it to pick from the service tags array, but that could also be changed to just mapping to an object in `lowerCaseServiceTags` that contains both variants and then performs a `find` (might be a bit more readable). 

Lemme know what you think.

P.S. I found the PR template a bit confusing as to whether you wanted me to include that in the description of the PR or to completely override it (as I've done now).

### CODE REVIEW

**Comment by Nezteb** [comment]
Hi @bastuijnman! Thanks for contributing to our OSS project! We'll work on getting this reviewed within the next couple weeks. I just wanted to keep you updated.

**Review by mnaumanali94 — APPROVED** [review]

**Comment by bastuijnman** [comment]
Any update regarding this PR? :)

**Review by Nezteb — APPROVED** [review]

**Review by Nezteb — CHANGES_REQUESTED** [review]
I'm not immediately sure why but the tests you've added aren't passing. 🤔 

`computeTagGroups leaves tag casing unchanged`
```
Error: expect(received).toEqual(expected) // deep equality

- Expected  - 2
+ Received  + 6

@@ -3,16 +3,17 @@
      Object {
        "items": Array [
          Object {
            "data": Object {
              "extensions": Object {},
-             "id": "?http-operation-id?",
+             "id": "2b447d075652c",
              "method": "get",
              "path": "/b",
              "request": Object {
                "body": Object {
                  "contents": Array [],
+                 "id": "1b5f96cfcd9cb",
                },
                "cookie": Array [],
                "headers": Array [],
                "path": Array [],
                "query": Array [],
@@ -20,10 +21,11 @@
              "responses": Array [],
              "security": Array [],
              "servers": Array [],
              "tags": Array [
                Object {
+                 "id": "c028e10befb64",
                  "name": "Beta",
                },
              ],
            },
            "name": "/b",
@@ -39,16 +41,17 @@
      Object {
        "items": Array [
          Object {
            "data": Object {
              "extensions": Object {},
-             "id": "?http-operation-id?",
+             "id": "2b547d0756761",
              "method": "get",
              "path": "/a",
              "request": Object {
                "body": Object {
                  "contents": Array [],
+                 "id": "c9a24d63f1884",
                },
                "cookie": Array [],
                "headers": Array [],
                "path": Array [],
                "query": Array [],
@@ -56,10 +59,11 @@
              "responses": Array [],
              "security": Array [],
              "servers": Array [],
              "tags": Array [
                Object {
+                 "id": "7d65d096f3728",
                  "name": "alpha",
                },
              ],
            },
            "name": "/a",
```

`computeTagGroups matches mixed tag casing`
```
Error: expect(received).toEqual(expected) // deep equality

- Expected  - 2
+ Received  + 6

@@ -3,16 +3,17 @@
      Object {
        "items": Array [
          Object {
            "data": Object {
              "extensions": Object {},
-             "id": "?http-operation-id?",
+             "id": "2b447d075652c",
              "method": "get",
              "path": "/b",
              "request": Object {
                "body": Object {
                  "contents": Array [],
+                 "id": "1b5f96cfcd9cb",
                },
                "cookie": Array [],
                "headers": Array [],
                "path": Array [],
                "query": Array [],
@@ -20,10 +21,11 @@
              "responses": Array [],
              "security": Array [],
              "servers": Array [],
              "tags": Array [
                Object {
+                 "id": "e01820f4e85ed",
                  "name": "beta",
                },
              ],
            },
            "name": "/b",
@@ -39,16 +41,17 @@
      Object {
        "items": Array [
          Object {
            "data": Object {
              "extensions": Object {},
-             "id": "?http-operation-id?",
+             "id": "2b547d0756761",
              "method": "get",
              "path": "/a",
              "request": Object {
                "body": Object {
                  "contents": Array [],
+                 "id": "c9a24d63f1884",
                },
                "cookie": Array [],
                "headers": Array [],
                "path": Array [],
                "query": Array [],
@@ -56,10 +59,11 @@
              "responses": Array [],
              "security": Array [],
              "servers": Array [],
              "tags": Array [
                Object {
+                 "id": "7d65d096f3728",
                  "name": "alpha",
                },
              ],
            },
            "name": "/a",
```

**Comment by bastuijnman** [comment]
The tests in fact look for the lowercase groups where the Zoom API spec (which they use) have uppercase entries. I'll rework the assertions to make them look for the exact casing that's in the spec

**Comment by bastuijnman** [comment]
Updated the tests to run properly now, one of the things I also noticed is the introduction of ID properties in the resulting object of the transformation.

I considered refactoring the tests to only check for the specific paths instead of a complete `toEqual` on the resulting objects but I think that's kind of out of scope for this PR. It might be something to look into as I was kind of confused as to where these ID's were coming from and it might break tests when introducing new properties into the stoplight structure even though contextually they shouldn't care about it.

**Review by Nezteb — APPROVED** [review]
Perfecto!

**Pull request merged**
