### PR TITLE
fix: rerenders and memoization and all that jazz

### LINKED ISSUE #1808: File Upload button not working properly. Some seconds after selecting some file to upload, Send Request form is being erased suddenly
## Describe the bug

File Upload button not working properly. Some seconds after selecting some file to upload, Send Request form is being erased suddenly

## To Reproduce

1. Given this OpenAPI document 
you can download the openAPI document or use the URL to try it online: 
https://www.pfx.com.br/openapi.yaml
https://elements-demo.stoplight.io/?spec=https://www.pfx.com.br/openapi.yaml#/operations/files/create

3. See error
In Endpoints > File > Create , just fill the Send Request form and select some file to upload
Some seconds after select some file, all the form will be erased.

## Expected behavior
The SendRequest form should keep with the selected/informed values. Otherwise you cannot send a request because all fields are empty, including the file uploaded.

## Additional context
We reproduced this problem in Stoplight Elements Embed via Web Component.
In the stoplight demo website the problem occurs:
https://elements-demo.stoplight.io/?spec=https://www.pfx.com.br/openapi.yaml#/operations/files/create

**Screenshots**
CleanShot 15-10-2021 as19 54 47
CleanShot 15-10-2021 as19 55 56

**Environment (remove any that are not applicable):**
 - OS: [OSX 11.6 BigSur]
 - Browser: [Chrome 94.0]
 - Browser: [Safari 15.0]
 - Platform: [Stoplight Elements Embed via Web Component]
 https://elements-demo.stoplight.io/?spec=https://www.pfx.com.br/openapi.yaml#/operations/files/create

### PR DESCRIPTION
**Pull request by mpodlasin**
Fixes #1808 

Also decreases the amount of re-renders the app does.

To test:

1. Run demo with the following file - https://www.pfx.com.br/openapi.yaml
2. You might need to enable CORS - I used https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en
3. Use upload form in TryIt.
4. Wait around a minute or so - changing the tabs also helped replicate the issue.
5. Expected result - file name is still present in try it (compare the behaviour with current `main`)

### CODE REVIEW

**Review by wmhilton — APPROVED** [review]
Awesome. My only thoughts are: we removed some Jakub-style defensive programming (`'document' in props && isPlainObject(props.document) ? Object(props.document) : undefined;`) so perhaps we should add a test to compensate, to make sure the components that use `InlineRefResolverProvider` don't crash under whatever circumstance Jakub was trying to defend against.

**Comment by Nezteb** [comment]
Were we ever able to reproduce this bug with a test?

**Comment by wmhilton** [comment]
@mpodlasin Noah's got a fair point about adding a test so it doesn't regress in the future

**Comment by mpodlasin** [comment]
I didn't replicate the *exact* problem, but I have written some unit tests targeting the route causes of issue.

I also reverted to the old logic of checking if an object is a "plain object", to avoid potentially breaking stuff.

**Comment by wmhilton** [comment]
Huzzah!

**Pull request merged**
