### PR TITLE
fix(dev-portal): add fetching state to search

### PR DESCRIPTION
**Pull request by bzmw**
Currently when you type into the search box while the http request is being completed you see "No results found".

This PR uses the react-query `isFetching` boolean to show "Fetching results..." while the query is in progress.

### CODE REVIEW

**Comment by mpodlasin** [comment]
Merging main will probably help with failing tests. We recently did an update to make them less flakey

**Comment by mpodlasin** [comment]
Thank you for the PR!

If I am being honest, I would prefer a different (granted, more complex) solution.

It would be better to show some kind of loading icon on the input itself, while keeping the results from the previous request.

This way we would avoid so much "jumping" in the results section. 🤔 

I am - ironically - finding it both distracting *and* unclear that a state changed with "text only" messaging.


https://user-images.githubusercontent.com/7916523/143565002-fd0371a7-1023-4533-96a2-93a1b5369d33.mov


What do you think?

**Comment by bzmw** [comment]
Main merged.

Yeah I envisioned a better loading spinner as well but I simply didn't have time for it so I threw this together.

**Comment by mpodlasin** [comment]
@mnaumanali94 what do you think? (check out the behaviour in the video I've posted in the previous comment)

**Comment by bzmw** [comment]
Closing in favour of #1894

**Pull request closed without merging**
