### PR TITLE
feat(dev-portal): search component

### PR DESCRIPTION
**Pull request by lottamus**
- Fixes https://github.com/stoplightio/elements/issues/1172
- Fixes https://github.com/stoplightio/platform-internal/issues/5654

Can see example of search working in our dev portal PR env: https://dev-portal-fuvmsk8zx-stoplight.vercel.app/docs/platform

image

### CODE REVIEW

**Comment by philsturgeon** [comment]
@lottamus will the markdown be rendered when this is done?

**Comment by philsturgeon** [comment]
An alternative would be strip it? If there’s no easy way then matching the result, rendering the full thing, then stripping HTML? 

We don’t need everything rendered just basic bold, italic, links, etc or at least remove the syntax? 

Either way, it currently just looks broken.

--
Phil Sturgeon
Product @ Stoplight.io

**Comment by philsturgeon** [comment]
Ok, spoke to @lottamus lets not block on search results.

**Review by mallachari — APPROVED** [review]
Works fine and looks good

**Pull request merged**
