### PR TITLE
feat: add ability to override code examples using `x-codeSamples`

### PR DESCRIPTION
**Pull request by weyert**
# Elements Default PR Template

In general, make sure you have: (check the boxes to acknowledge you've followed this template)

- [X] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)

Updates the `RequestSamples` and `TryItWithExamples`-components to support the `x-codeExamples` vendor extension on a http operation schema. 

refs #2453

### CODE REVIEW

**Comment by mnaumanali94** [comment]
@weyert Hey! Thank you for the contribution.  Were you going for x-codeexamples or was it supposed to be x-codesamples? 

x-codesamples is generally what we see being used in the industry.

**Comment by weyert** [comment]
Oh sorry, my bad. I am happy to update it.  You are totally right. 
I am not sure if we would like to remap support mappings from other views (E.g. redly) to the values that Elements is expecting?

**Comment by brendarearden** [comment]
> I am not sure if we would like to remap support mappings from other views (E.g. redly) to the values that Elements is expecting?

I am not sure what you mean by this? is redly using a different overriding code example x extension?

**Comment by weyert** [comment]
> > I am not sure if we would like to remap support mappings from other views (E.g. redly) to the values that Elements is expecting?
> 
> I am not sure what you mean by this? is redly using a different overriding code example x extension?

Sorry, I meant Redocly and others might use a different naming convention for the `language`, e.g. `shell` vs `bash` etc. I think we are fine for Read.me version of doing this, though.

**Comment by brendarearden** [comment]
> Sorry, I meant Redocly and others might use a different naming convention for the `language`, e.g. `shell` vs `bash` etc. I think we are fine for Read.me version of doing this, though.

Gotcha. We don't need to do the remapping as part of this, but would you open a separate issue for the remapping?

**Comment by weyert** [comment]
> Gotcha. We don't need to do the remapping as part of this, but would you open a separate issue for the remapping?

Sure, happy to do that.

**Review by brendarearden — APPROVED** [review]
This looks good - I tested out the storybook examples and it appears to be working!

**Review by brendarearden — CHANGES_REQUESTED** [review]
Actually, after futher testing, it looks like the state is getting stuck when going to select different code samples

**Comment by weyert** [comment]
Hmm, bummer, wondering if it's incorrect management of the `isStale`-variable?

**Comment by weyert** [comment]
Don't want to sound rude but I would prefer Stoplight's resources would be spend on my other PR https://github.com/stoplightio/elements/pull/2545 which would allow me to stop using my fork of Elements. This PR was just a nice improvement.

**Comment by brendarearden** [comment]
@weyert this PR overlapped with a feature request from our product team, so it was a higher priority in the backlog. I appreciate you letting us know though and we make sure your other PR is moved up in priority! hopefully we will be able to get you unforked soon!

**Review by brendarearden — APPROVED** [review]
looks good!

**Pull request merged**
