### PR TITLE
fix: maxHeight for panels

### PR DESCRIPTION
**Pull request by paulatulis**
Should address #1664 specifically request sample panel was unnecessarily long. Request body looks to already be fixed.

before: 
Screen Shot 2021-08-23 at 10 35 45 AM

after:
Screen Shot 2021-08-23 at 10 35 22 AM

### CODE REVIEW

**Comment by mnaumanali94** [comment]
request sample fix still should be merged, no?

**Review by wmhilton — APPROVED** [review]
Ah good old "px"

**Comment by wmhilton** [comment]
@paulatulis FYI I've changed both this one and #1710 from "chore" to "fix" because the distinction is not how small the PR is, but whether they have an impact on customers and thus need to be released. Chores might include, fixing typos in the README or changing the CI pipeline to be faster or something. Both of these changes make a difference to how the application works from a customer perspective!

**Comment by paulatulis** [comment]
> @paulatulis FYI I've changed both this one and #1710 from "chore" to "fix" because the distinction is not how small the PR is, but whether they have an impact on customers and thus need to be released. Chores might include, fixing typos in the README or changing the CI pipeline to be faster or something. Both of these changes make a difference to how the application works from a customer perspective!

Thank you! I get into the habit of using chore and forget to update. Will try to make it a point to be more mindful going forward.

**Pull request merged**
