### PR TITLE
fix: automated release

### LINKED ISSUE #1330: Fix the automated release process
Right now our auto-release process is broken. This is supposedly because Yarn will not read an npmrc.

[See Slack Discussion](https://stoplight-internal.slack.com/archives/CN2781QQZ/p1621613869062200?thread_ts=1621517027.048000&cid=CN2781QQZ)

Fix it.

### PR DESCRIPTION
**Pull request by marcelltoth**
Resolves #1330 

**Warning**: To verify the CI changes, this PR will attempt to trigger an `@elements/core` build.

## Summary

Hopefully that added command in the config will make publishing succeed.

## Extra treats

I packed two extra pieces of cleanup into this PR.

1. Moved the release script into `package.json` so we can simply run it locally by `yarn run release` without having to worry about copying the command from CircleCI.
2. Fixed an issue where dev-portal would depend on an earlier version of core (which made it install from NPM -> hence the yarn.lock diff). These kinds of problems could likely be eliminated with pnpm's (or yarn berry's)  [workspaces feature](https://pnpm.io/workspaces#workspace-protocol-workspace)

### CODE REVIEW

**Review by philsturgeon — APPROVED** [review]
Looks good. Maybe also delete the release.sh?

**Comment by marcelltoth** [comment]
> Looks good. Maybe also delete the release.sh?

I must be blind but... is that still around?

**Review by mmiask — APPROVED** [review]
Looks good! Let's try it 🤞

**Comment by marcelltoth** [comment]
I'm holding off with this until Monday as I'll spend the rest of my day on presentations, and will be off tomorrow. Feel free to take over and merge it if you specifically need it for something though.

**Pull request merged**
