### PR TITLE
fix: elements-examples studio-demo Todo API

### PR DESCRIPTION
**Pull request by mnaumanali94**

### CODE REVIEW

**Review by wmhilton — APPROVED** [review]

**Review by P0lip — CHANGES_REQUESTED** [review]
We have more broken examples, i.e. https://github.com/stoplightio/elements/blob/39b2f3fd8b53391ad9493d42a8db947425f02014/packages/elements/src/web-components/__stories__/Api.stories.tsx#L34


I'd say we should just upload the files here if we don't have any todo

**Comment by wmhilton** [comment]
@P0lip I was just about to suggest that as a followup!

**Comment by wmhilton** [comment]
Yes, lets move the files we care about into the stoplightio/elements repo. That way it won't have any weird external dependency.

**Review by P0lip — APPROVED** [review]

**Comment by P0lip** [comment]
> That could be an issue if we ever want to update it.

hmm yeah, but hopefully it doesn't change too often.

**Pull request merged**
