### PR TITLE
chore: use stable version

### PR DESCRIPTION
**Pull request by philsturgeon**
We've been stable a while but didnt update the docs. Oops!

### CODE REVIEW

**Review by mpodlasin — APPROVED** [review]
Yup 😅

**Comment by bzmw** [comment]
@philsturgeon the tags and releases on this repo also do not reflect that 7.0 is the latest and greatest.

**Comment by philsturgeon** [comment]
@bzmw we no longer use tags, as this is a monorepo now and that gets a bit funny. I've made a note to look into lerna + releases again, but for now I've just turned Releases off. Thanks!

**Comment by philsturgeon** [comment]
@bzmw we no longer use tags, as this is a monorepo now and that gets a bit funny. I've made a note to look into lerna + releases again, but for now I've just turned Releases off. Thanks!

**Pull request merged**
