### PR TITLE
Feat: Project ToC Responsive Style Adjustments

### PR DESCRIPTION
**Pull request by paulatulis**
# Elements Default PR Template

I went ahead and made this a minor version change since it's not a bug fix, but if it should be versioned differently, please let me know!

As you will see, the icons are not the [desired](https://www.figma.com/file/BZZk7EIPmOEzKfn4TE5psF/Docs-Enhancements-2023?type=design&node-id=928-8593&mode=design&t=u4NLUp6ntgJI2C1N-0) 'far' [prefix](https://fontawesome.com/docs/web/add-icons/how-to#classic-family), and I don't know the best way to make this work with the way elements is configured. If this is a blocker, I do need some help figuring it out. 

@noor-ahmad tagging you here and adding you as a reviewer to give your thoughts on the icon issue. 

This PR changes the style of the project ToC in the following ways: 
- Icons are all on the left side of the items on screens of all sizes
- When `isInResponsiveMode` is passed through to the ToC component
      - background is lightened
      - items get larger
      - font gets larger

To interact with the changes, check out the "Embedded Search" story inside the "Search" story as well as the "TableOfContents" story in elements-dev-portal .

In general, make sure you have: (check the boxes to acknowledge you've followed this template)

- [x] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)

#### Other Available PR Templates:

- Release: https://github.com/stoplightio/elements/compare?template=release.md
  - [x] [Read the release section of `CONTRIBUTING.md`](../CONTRIBUTING.md#releasing-elements)

### CODE REVIEW

**Review by kaylachun — APPROVED** [review]
This looks great Paula!

**Review by mallachari — APPROVED** [review]

**Comment by noor-ahmad** [comment]
The font weights are not a blocker for me especially if Elements is being tricky, but if you want to give this a try for the icons:
`fal fa-cube` instead of `far`

It is a little confusing because they changed the prefix to actually spell out the weight
`<FontAwesomeIcon icon="fa-light fa-cube" />`

If none of these work, we can leave it as is!

**Comment by paulatulis** [comment]
@noor-ahmad Thank you so much for the feedback! 

I added some padding at the top of the component block in storybook, but since the input, search, and toc elements are all à la carte, we can make more updates to how the entire piece behaves/looks when this gets implemented in platform internal. I will make sure to include you as a reviewer for that PR as well. 

I wasn't able to get the icon to show up even with your recommended strategy :/ 
I'm not positive, but I _think_ that we keep it limited to the free icons for elements since it's open source.

**Review by noor-ahmad — APPROVED** [review]
No worries at all, everything else looks great! I'll approve this PR :)

**Pull request merged**
