### PR TITLE
Supports multiple tags by operations

### LINKED ISSUE #2262: Multiple Tags Of The Operation
## Context

When the operation contains multiple tags, the user should be able to see the operation under each specified tag in the Table of Contents.

## Current Behavior

The current version does the grouping by the first met tag in an operation:
image

## Expected Behavior

According to SwaggerHub, the expected behavior should look like in the picture below:
image

## Possible Solution(s)

Synchronize the logic with SwaggerHub by showing the Operation inside the each mentioned tag in the TOC.

### PR DESCRIPTION
**Pull request by EwenQuim**
# Supporting multiple tags for one operation

- [x] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)

Fixes #2262. We highly need it for [Fuego](https://github.com/go-fuego/fuego) 🙏🏼

### CODE REVIEW

**Comment by EwenQuim** [comment]
I don't know why it fails on Angular but works for React, I didn't touch the framework part, only the core. Works locally too.

And I can't access CircleCI logs :/ This might be a one-time miss, can you re-run the tests please?

**Comment by EwenQuim** [comment]
@lukasikp @darekplawecki is it possible to review if you have time, please?

**Comment by mrydz** [comment]
Our team would also love for this feature to be merged.

**Comment by EwenQuim** [comment]
This PR has very few lines and passes the tests.
It corrects an issue that have a few thumbs up and is very clear.

Is it possible to review it?  It should be quick and unlock a lot of people!
@mnaumanali94 @lukasikp @darekplawecki

**Review by ben-smartbear — APPROVED** [review]

**Review by darekplawecki — APPROVED** [review]

**Comment by ben-smartbear** [comment]
Merged! Thanks for the PR!

**Comment by weyert** [comment]
Thanks for merging. I will update my PR as it is probably conflicting now.

**Comment by EwenQuim** [comment]
Which one are you talking about @weyert ?

**Comment by mrydz** [comment]
I'm guessing this one https://github.com/stoplightio/elements/pull/2603

**Comment by EwenQuim** [comment]
This is not the same feature :) 

What this feature means is to support the fact that an operation can have multiple tags. It's not the same as x-tagGroup

**Comment by mrydz** [comment]
Right, different operations, but impacts the same code for display so they need to update their PR to account for the changes in this PR.  

image

**Comment by EwenQuim** [comment]
My bad I thought they wanted to close their PR, I'm just tired, sorry about that

**Pull request merged**
