### PR TITLE
chore: bump jsv to show more combiners

### PR DESCRIPTION
**Pull request by paulatulis**
# Elements Default PR Template

Bumps JSV to address [9513](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/platform-internal/9513)

In general, make sure you have: (check the boxes to acknowledge you've followed this template)

- [x] Read [`CONTRIBUTING.md`](https://github.com/stoplightio/elements/blob/main/CONTRIBUTING.md)

#### Other Available PR Templates:

- Release: https://github.com/stoplightio/elements/compare?template=release.md
  - [x] [Read the release section of `CONTRIBUTING.md`](https://github.com/stoplightio/elements/blob/main/CONTRIBUTING.md#releasing-elements)

Here's a screenshot from elements-core storybook as sanity check:
Screen Shot 2022-01-05 at 10 59 06 AM

### CODE REVIEW

**Comment by paulatulis** [comment]
> Fix ya links! :)

Oops! I just went and found them. I didn't know the reviewer also needed to sign off that they've read CONTRIBUTING.md :D 
Updated.

**Comment by jgreen44** [comment]
> > Fix ya links! :)
> 
> Oops! I just went and found them. I didn't know the reviewer also needed to sign off that they've read CONTRIBUTING.md :D Updated.

Said tongue-in-cheek. You know I can't read anyway. Currently going over the other issue/pr so I know what we're bumping.

**Comment by paulatulis** [comment]
You have to add the :trollface: or the winky face so I know ;)!

(:trollface: )

**Review by jgreen44 — APPROVED** [review]

**Comment by lottamus** [comment]
@paulatulis @jgreen44 don't forget to call `yarn` to update the `yarn.lock` after changing a package dep:

image

**Comment by paulatulis** [comment]
> @paulatulis @jgreen44 don't forget to call `yarn` to update the `yarn.lock` after changing a package dep:
> 
> image

Ah sorry about that @lottamus and thanks for flagging. Will do going forward. Shall I go ahead and open a fresh PR now that takes care of it or is there a better way?

**Pull request merged**
