### PR TITLE
fix: allow large specs to load schema

### PR DESCRIPTION
**Pull request by paulatulis**
Addresses #[7923](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/platform-internal/7923)

Before: page becomes unresponsive when clicking around to models with circular refs

After:

### CODE REVIEW

**Comment by wmhilton** [comment]
Did we figure out whether the issue was circular refs or just "big models"? because limiting the depth to 4 seems to imply it's big models.

**Comment by paulatulis** [comment]
> Did we figure out whether the issue was circular refs or just "big models"? because limiting the depth to 4 seems to imply it's big models.

@wmhilton I don't think we confirmed one way or the other. Could it not be that it's both? 

Also, if we don't limit this number, won't the example be extremely long to the point someone is scrolling forever? Is it helpful from a product standpoint to have such a long example?

**Comment by Nezteb** [comment]
> ```
> ../packages/elements-core/src/utils/exampleGeneration.ts:82:5 - error TS2345: Argument of type '{ maxSampleDepth: number; }' is not assignable to parameter of type 'Options'.
>   Object literal may only specify known properties, and 'maxSampleDepth' does not exist in type 'Options'.
> 
> 82     maxSampleDepth: 4,
>        ~~~~~~~~~~~~~~~~~
> 
> 
> Found 1 error.
> ```

🤔

**Comment by paulatulis** [comment]
> > ```
> > ../packages/elements-core/src/utils/exampleGeneration.ts:82:5 - error TS2345: Argument of type '{ maxSampleDepth: number; }' is not assignable to parameter of type 'Options'.
> >   Object literal may only specify known properties, and 'maxSampleDepth' does not exist in type 'Options'.
> > 
> > 82     maxSampleDepth: 4,
> >        ~~~~~~~~~~~~~~~~~
> > 
> > 
> > Found 1 error.
> > ```
> 
> 🤔

This is because `json-schema-sampler` hasn't been released yet after [this PR](https://github.com/stoplightio/json-schema-sampler/pull/20) was just approved. It still thinks this is not a prop.

**Review by wmhilton — APPROVED** [review]
I like it!

**Pull request merged**
