### PR TITLE
chore: release elements

### PR DESCRIPTION
**Pull request by jgreen44**
Reference: #8606

elements: `7.3.11` -> `7.3.12`
elements-core: `7.3.10` -> `7.3.11`
elements-dev-portal: `1.4.7` -> `1.4.8`

### CODE REVIEW

**Review by wmhilton — CHANGES_REQUESTED** [review]
Almost! In order for `elements-dev-portal` to use the new `elements-core` release, you need to bump the version in `packages/elements-dev-portal/package.json` line 51

**Review by wmhilton — APPROVED** [review]
Yup! That should do the trick!

**Comment by wmhilton** [comment]
@mpodlasin recommends bumping elements (and the version of elements-core in elements dependencies) to be safe

**Comment by jgreen44** [comment]
@wmhilton @mpodlasin : Can we Zoom together before bumping?

**Review by mpodlasin — APPROVED** [review]
Screenshot 2021-11-22 at 19 13 04

**Pull request merged**
